/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CatAddItem: typeof import('./components/left-aside/CatAddItem.vue')['default']
    CatSearchItem: typeof import('./components/left-aside/CatSearchItem.vue')['default']
    CatTree: typeof import('./components/left-aside/CatTree.vue')['default']
    CatTreeNode: typeof import('./components/left-aside/CatTreeNode.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ExpandableInput: typeof import('./components/bottom-input/ExpandableInput.vue')['default']
    LeftAside: typeof import('./components/left-aside/LeftAside.vue')['default']
    MainItem: typeof import('./components/main/MainItem.vue')['default']
    MainList: typeof import('./components/main/MainList.vue')['default']
    MdInput: typeof import('./components/bottom-input/MdInput.vue')['default']
    MyClickIcon: typeof import('./components/custom/MyClickIcon.vue')['default']
    MyHeader: typeof import('./components/header/MyHeader.vue')['default']
    MyLinkIcon: typeof import('./components/custom/MyLinkIcon.vue')['default']
    OperationButtons: typeof import('./components/main/OperationButtons.vue')['default']
    PreviewImages: typeof import('./components/main/PreviewImages.vue')['default']
    ProfileDialog: typeof import('./components/left-aside/ProfileDialog.vue')['default']
    UserItem: typeof import('./components/left-aside/UserItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
